branches:
  only:
    - master

sudo: required
#dist: precise # require Precise infrastructure: fully virtualized, 7.5GB RAM
dist: trusty
group: edge # New android image with last {SDK,Build,Platform} tools
language: android
jdk:
  - oraclejdk8
env:
  global:
  - ABI=armeabi-v7
  - TAG=google_apis
  
  matrix:
    - API=16
    - API=19
    - API=22
    - API=23
    - API=25
matrix:
  fast_finish: true
android:
  components:
    - tools
    - platform-tools
    - tools # Fix SDK Tools https://github.com/travis-ci/travis-ci/issues/6122
    - build-tools-25.0.3
    - android-25 # target SDK version
    - android-$API
    - extra-android-support
    - extra-android-m2repository
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper
before_install:
    - export EMULATOR="system-images;android-${API};${TAG};${ABI}" # Used to install/create emulator

before_script:
    # Avoid useless reupload of cache after every build, see https://docs.travis-ci.com/user/languages/android
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
    - sdkmanager "$EMULATOR"
      # Create Android Virtual Device with current config, saying no to custom build
    - echo no | avdmanager create avd -n test -k $EMULATOR -f --abi $ABI --tag $TAG
      # Run emulator and wait until it is ready, then send KEYCODE_MENU to unlock the phone
    - emulator -avd test -no-skin -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &
script:
    - set -o pipefail
    - travis_wait bash run_test.sh
